import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LogoutButton from "./components/LogoutButton"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-4 items-center px-4 py-3 border-b border-gray-200 bg-white">
            <Link href="/dashboard" className="text-sm font-medium text-gray-700">Overview</Link>
            <Link href="/transactions" className="text-sm font-medium text-gray-700">Transactions</Link>
            <Link href="/form" className="text-sm font-medium text-gray-700">Add</Link>
            <div className="ml-auto">
                <LogoutButton />
            </div>
        </nav> 
        {children}
      </body>
    </html>
  );
}